### ISSUE TITLE
Updated ESPhome to 2021.9.0 and zones lost supervision

### ISSUE THREAD

**Issue by AlexandreUSA** [Dilbert66/esphome-vistaECP#55]
Last night, I updated ESPhome to 2021.9.0 from 2021.8.2. After a minute or so, my vista 21IP keypads went into bunch of errors. I had to unplug my vistaalarm system to go back to normal. Anyone else got into some trouble while updating to ESPhome 2021.9?

Lot of messages with error code 354 [Comm Fail (log only)] or 383 [Supervision Auxiliary Wire Zone]. All related to zone 9 to 14 (extander)
```
003 E354 Z107 P0

009 E382 Z009 P1
```

I restarted the VistaAlarm system today and no more errors on the keypads. However, I still have this log entry in the vistaalarm log:

`[13:57:06][D][text_sensor:015]: 'vistaalarm Lrr Msg': Sending state '382: Loss of supervision  RPM zone 10'`

Do we have an issue here with the latest ESPhome release?

**Comment by Dilbert66** [comment]
Are you using the virtual expander or is this extender a physical extender on the panel?   When using a virtual expander and your restart, the panel will error since it is not getting a response from the ESP so will generate errors.  You clear erros as usual by enteriing your accesscode then 1 twice.

**Comment by AlexandreUSA** [comment]
It is a physical extender. No change in my vistaalarm.yaml. I could not clear the errors either using the access code twize.

```
substitutions:
  systemName: "vistaalarm"
  accessCode: !secret access_code #Only comes into effect if needed for arming and quickarm is not set
  keypadAddr: "19" #set this to an unused keypad address slot. Make sure to enable it in  your vista panel programming
  
  #esp32 pins:
  rxPin: "22" #GPIO pin to use for data receive (yellow line) 
  txPin: "21" #GPIO pin to use for data transmit (green line)
  monitorPin: "18" #GPIO pin to use for monitoring module traffic such as RF or Expanders . Set to -1 to disable
  
  # module addresses:
  # 07 4229 zone expander  zones 9-16
  # 08 4229 zone expander zones 17-24
  # 09 4229 zone expander zones 25-32
  # 10 4229 zone expander zones 33-40
  # 11 4229 zone expander zones 41 48
  # 12 4204 relay module  
  # 13 4204 relay module
  # 14 4204 relay module
  # 15 4204 relay module
  expanderAddr1: "0" # 1st zone expander emulator (4229) address to use . Set to 0 to disable. 
  expanderAddr2: "0" # 2nd expander emulator address to use . Set to 0 to disable. 
  
  relayAddr1: "0" # relay module emulation (4204) addresses. Set to 0 to disable
  relayAddr2: "0"
  relayAddr3: "0"
  relayAddr4: "0"
```
